### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by MoritzStefaner** [josefaidt/svelte-themer#24]
Hi,

this looks great — do you know if it could work in IE11? 
https://svelte-themer.now.sh/ does not seem to work out of the box, but are you aware if any of the polyfills mentioned here: https://stackoverflow.com/questions/46429937/ie11-does-a-polyfill-script-exist-for-css-variables could make it work?

Thanks!

**Comment by josefaidt** [comment]
Hi @MoritzStefaner ! Thanks for filing an issue! I'll start taking a look at this

**Comment by MoritzStefaner** [comment]
Thanks!

**Comment by MoritzStefaner** [comment]
Hooray! Thank you!
