### ISSUE TITLE
can't reproduce it :/

### ISSUE THREAD

**Issue by guilhermedelyra** [josefaidt/svelte-themer#25]
using svelte basic template...

<details>
<summary>
<code>Folder structure:</code> ⤵️
</summary>

![image](https://user-images.githubusercontent.com/23236957/107454197-5512e700-6b2b-11eb-880e-d2a4134aa67c.png)

</details>

<details>
<summary>
<code>package.json</code> ⤵️
</summary>

![image](https://user-images.githubusercontent.com/23236957/107454110-2dbc1a00-6b2b-11eb-8e71-18e4dee32632.png)

</details>

<details>
<summary>
<code>main.js</code> ⤵️
</summary>

![image](https://user-images.githubusercontent.com/23236957/107454387-acb15280-6b2b-11eb-80a1-a84598255c9a.png)

</details>

<details>
<summary>
<code>themes.js</code> ⤵️
</summary>

![image](https://user-images.githubusercontent.com/23236957/107454137-3ca2cc80-6b2b-11eb-8b7a-81f96a545d2c.png)

</details>

<details>
<summary>
<code>App.svelte</code> ⤵️
</summary>

![image](https://user-images.githubusercontent.com/23236957/107454163-47f5f800-6b2b-11eb-8f77-986e01bb98d5.png)

</details>

Results:

<details>
<summary>
<code>Light</code> ⤵️
</summary>

![image](https://user-images.githubusercontent.com/23236957/107454243-678d2080-6b2b-11eb-9cd5-d03c2d3dd3ff.png)

</details>

<details>
<summary>
<code>Dark</code> ⤵️
</summary>

![image](https://user-images.githubusercontent.com/23236957/107454298-87244900-6b2b-11eb-8eb1-ee91ef5b5670.png)

</details>

Is there something I'm missing?

**Comment by josefaidt** [comment]
Hi @guilhermedelyra yes you'll need to add the following CSS to your App file

```html
<style>
  :global(html) {
    background-color: var(--theme-colors-background);
    color: var(--theme-colors-text);
  }
</style>
```

**Comment by guilhermedelyra** [comment]
> Hi @guilhermedelyra yes you'll need to add the following CSS to your App file
> 
> ```html
> <style>
>   :global(html) {
>     background-color: var(--theme-colors-background);
>     color: var(--theme-colors-text);
>   }
> </style>
> ```

Ohhh thank you! 😁
