### ISSUE TITLE
Uncaught TypeError: ThemeWrapper is not a constructor

### ISSUE THREAD

**Issue by AnicetNgrt** [josefaidt/svelte-themer#33]
Hi.

Using `sveltejs/template` with nothing modified except `svelte-themer ^0.4.8` installed as a dev dependency.

```js
// App.svelte
<script>
	import { ThemeWrapper, ThemeToggle } from 'svelte-themer'
</script>
  
<ThemeWrapper>
	<main>
		<h1>svelte themer</h1>
		<ThemeToggle />
	</main>
</ThemeWrapper>

<style>
	:global(html) {
		background-color: var(--theme-colors-background, initial);
		color: var(--theme-colors-text, initial);
	}
</style>
```

`npm run dev`

In the browser console all I get is

```
Uncaught TypeError: ThemeWrapper is not a constructor
    create_fragment bundle.js:2449
    init index.mjs:1500
    App bundle.js:2518
    app main.js:3
    <anonymous> bundle.js:2536
```

I'm a Svelte noob, am I missing something?

Thank you for your consideration.

**Comment by josefaidt** [comment]
Hey :wave: thanks for raising this! I'm seeing this as well in a bare bones codesandbox instance. I think I messed the ES build up when aiming to support SSR in svelte-kit. After reverting that change it seemed to fix things (published to `next`)
https://codesandbox.io/s/hungry-haze-0lvm8?file=/App.svelte

Looking into producing the proper ssr bundle

**Comment by josefaidt** [comment]
@AnicetNgrt this should be fixed in 0.4.9!

**Comment by AnicetNgrt** [comment]
Thank you! About to check this out

**Comment by AnicetNgrt** [comment]
Upgraded to 0.4.9, looks like I still have it...

**Comment by josefaidt** [comment]
Hmm let me take a deeper look into what's going on.

**Comment by josefaidt** [comment]
@AnicetNgrt I'm not able to reproduce this with the template you mentioned using

```
npx degit sveltejs/template my-app
```

and adding svelte-themer as a devDependency or dependency should work with that setup

**Comment by AnicetNgrt** [comment]
I'll try to restart from scratch tomorrow @josefaidt

**Comment by AnicetNgrt** [comment]
@josefaidt It's working after restarting from scratch. Must have been a mistake on my side. Thanks for the fast fix!
